# ! This is a file for http test (vscode extension: Rest Client)

# healthCheck
GET http://localhost:3003/api/healthCheck

###
# User Sign Up API
POST http://localhost:3003/api/user/signup
Content-Type: application/json

{
    "name": "vic",
    "email": "12345@gmail.com",
    "password": "12345"
}

###
# User Sign In API
POST http://localhost:3003/api/user/signin
Content-Type: application/json

{
    "email": "12345@gmail.com",
    "password": "12345"
}

###
# Resume Get API

GET http://localhost:3003/api/resume/get?resumeId=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InZpYyIsImVtYWlsIjoiMTIzNDVAZ21haWwuY29tIiwiaWF0IjoxNjg0MTE2NzI3fQ.HthT86wE0Eekbuxzdno0yZD0zUbLmHqlD1m4i42PJ4s

{

}
