name: markdown_resume_maker build

on:
  push:
    branches:
      - ec2_testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          pwd;
          cd backend
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/markdown_resume_maker:backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/markdown_resume_maker:backend
          
          cd ..
          cd frontend
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/markdown_resume_maker:frontend .
          docker push  ${{ secrets.DOCKERHUB_USERNAME }}/markdown_resume_maker:frontend
          
      
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin
            cd code/markdown_resume_maker
            git --version
            git pull
            git checkout ec2_testing
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin;
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/markdown_resume_maker:backend
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/markdown_resume_maker:frontend
            docker-compose down --rmi all
            docker-compose up -d;
            docker-compose ps;
            docker image prune -af